# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
#     vb.cpus = 2
#     vb.gui = false
   end

  config.vm.define "c6" do |c6|
    c6.vm.box = "centos/6"
    c6.vm.hostname = "c6"
#     c6.vm.box_check_update = false
#     c6.vm.network "forwarded_port", guest: 80, host: 8080
#     c6.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
#     c6.vm.network "private_network", ip: "192.168.33.10"
#     c6.vm.network "public_network"
#     c6.vm.synced_folder "../data", "/vagrant_data"
    c6.vm.provision "shell", inline: <<-SHELL
      yum install -y python libselinux-python
    SHELL

    c6.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "pb-centos.yaml"
      # ansible.raw_arguments = ["--verbose"]
    end
  end
  
  config.vm.define "c7" do |c7|
    c7.vm.box = "centos/7"
    c7.vm.hostname = "c7"
    c7.vm.provision "shell", inline: <<-SHELL
      yum install -y python libselinux-python
    SHELL

    c7.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "pb-centos.yaml"
    end
  end

  # https://linuxize.com/post/how-to-install-python-on-centos-8/
  config.vm.define "c8" do |c8|
    c8.vm.box = "centos/8"
    c8.vm.hostname = "c8"
    c8.vm.provision "shell", inline: <<-SHELL
      dnf install -y epel-release
      dnf makecache
      dnf install -y ansible
      alternatives --set python /usr/bin/python3
    SHELL

    c8.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "pb-centos8.yaml"
    end
  end

  config.vm.define "f32" do |f32|  # python already installed
    f32.vm.box = "fedora/32-cloud-base"
    f32.vm.hostname = "f32"
    f32.vm.provision "shell", inline: <<-SHELL
      echo "IGNORE THIS:  [WARNING]: Module invocation had junk after the JSON data:
AttributeError(\"module \'platform\' has no attribute \'dist\'\")
KeyError(\'ansible_os_family\')"
#       dnf install -y python
    SHELL

    f32.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "pb-fedora.yaml"
    end
  end


  config.vm.define "u16" do |u16|
    u16.vm.box = "ubuntu/xenial64" # python not preinstalled
    u16.vm.hostname = "u16"
    u16.vm.provision "shell", inline: <<-SHELL
      apt-get -y install python
    SHELL

    u16.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "pb-ubuntu.yaml"
    end
  end

  config.vm.define "u18" do |u18|
    u18.vm.box = "ubuntu/bionic64" # python not preinstalled
    u18.vm.hostname = "u18"
    u18.vm.provision "shell", inline: <<-SHELL
      apt-get -y install python
    SHELL

    u18.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "pb-ubuntu.yaml"
    end
  end

# https://www.reddit.com/r/Ubuntu/comments/ga187h/focal64_vagrant_box_issues/
  config.vm.define "u20" do |u20|   # python not installed...must be python not python2
    u20.vm.box = "bento/ubuntu-20.04"
#     u20.vm.box = "ubuntu/focal64"  # 5/13/20 box missing key package
    u20.vm.hostname = "u20"
    u20.vm.provision "shell", inline: <<-SHELL
      apt-get -y install python
      apt autoremove -y
    SHELL

    u20.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "pb-ubuntu.yaml"
    end
  end

end
